### ISSUE TITLE
expansion of VoteEvent.classification enumeration

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#12]
see opencivicdata/pupa#153 and related issues

**Comment by jamesturk** [comment]
motion_classification | count
-----------------------|--------
 {}                    |  11886
 {amendment}           |   1217
 {bill}                |    602
 {committee}           |   9515
 {committee-passage}   |   5797
 {failure,reading-3}   |      5
 {other}               | 187440
 {passage}             | 301011
 {passage,reading-3}   |   3343
 {passed}              |   1761
 {reading-1}           |    136
 {reading-3}           |  31049

**Comment by jamesturk** [comment]
I'm planning to go with these:
- amendment
- committee-passage
- passage
- reading-3
- reading-1

this would mean updating some code that currently uses these:
- passed -> passage
- failure -> passage
- committee -> committee-passage
- bill -> {}
- other -> {}

@showerst - thoughts on this set for now?

**Comment by showerst** [comment]
Makes sense to me!

**Comment by estaub** [comment]
I know this is ambitious, but you might consider attempting to design these so that, when combined with a set of bill states that may not be present in state data but can be inferred, each [ classification, pass-or-fail ] tuple is an event that can be used to create a useful state machine.  

If you haven't already, I'd survey a few states that provide a meaningful classification, to get a decent first set that doesn't omit some really common cases.  For example, in NH there are votes to return-to-committee, and to kill (quaintly named "ITL" for "inexpedient to legislate".  The meaning of votes in these cases is inverted; a "yes" ITL vote is _against_ passage.  I've no idea how common this kind of thing is.  Don't look at what the scrapers are producing, look at the raw data.

**Comment by jamesturk** [comment]
Hey Ed!  Good to hear from you.

I like that idea a lot, I want to initially tighten the scrapers that are
sending bad/redundant data into the classification as a first step, but I
definitely think that for states that provide other classifications we can
& should expand these.  Fortunately that's now an easier process, so this
first step won't hamper future attempts to amend the list.

**Comment by estaub** [comment]
The set of NH terms is unimportant (beyond the scraper) but a few years ago I boiled the legislature floor (non-committee) votes down to this abstract set.  The names are mine.

- pass Committee of Conference Report
- amend
- kill
- table
- pass
- pass amended
- rerefer to committee

**Comment by jamesturk** [comment]
initial enforcement is added in openstates-core 4.5, leaving this open for future work

**Comment by jamesturk** [comment]
with latest updates to schema looking good for now and we can add more later as needed case-by-case
