### ISSUE TITLE
Lots of Missing voter_id data on opencivicdata_personvote table for pg_dump endpoint

### ISSUE THREAD

**Issue by LukeClancy** [openstates/issues#189]
**Issue Description:**

Using a database originating from the pg_dump endpoint (2020-12) I have noticed that there are alot of rows in the opencivicdata_personvote table where the voter_id is NULL. It is worth noting that the voter_name is still set properly for all these rows.

- Number of votes with a voter_name but without a voter_id: 10119945
- query for above: select COUNT(*) FROM opencivicdata_personvote WHERE voter_id is NULL and voter_name is not NULL;
- Number of votes with a voter_name and with a voter_id: 15023122
- query for above: select COUNT(*) FROM opencivicdata_personvote WHERE voter_id is not NULL and voter_name is not NULL;

Percent of records without voter_id: 40%

Insight: If this doesn't align with api data, perhaps this issue has to do with when the database was dumped? Perhaps it was dumped at a  bad time in-between a few sql queries. I will check the endpoint again in a few days and update.

**URL where this issue may be seen (API or OpenStates.org):**

The pgdump links:
https://data.openstates.org/postgres/schema/2020-12-schema.pgdump
https://data.openstates.org/postgres/monthly/2020-12-public.pgdump

This is besides the point - but the above two files should really be behind some sort of api authentication

**Comment by jamesturk** [comment]
See #22.

This is known and matching legislators is an ongoing effort, probably a focus of
spring 2021 after sessions are underway and being ingested, but any help
would be appreciated.

**Comment by LukeClancy** [comment]
Thanks for the information and reply!

Is the code matching peoples names taking place in: https://github.com/openstates/people/blob/main/scripts/unmatched_legislators.py ? How do I setup the software for development? Are you currently using a [Machine Learning based algorithm for matching](https://towardsdatascience.com/fuzzy-name-matching-with-machine-learning-f09895dce7b4) or is it string matching? I am willing to give it a shot

**Comment by jamesturk** [comment]
We're aiming at a more manual approach than machine learning/etc. because
our priority is precision and don't have the capacity to audit the results
at the appropriate level for automated matching.

So we're building on string matching with aliases as mentioned in the
parent issue.  The good news is that there aren't that many legislators
relatively speaking, and their aliases rarely change (maybe 1-2 times per
session).  The next step is to actually work to add the aliases present in
the data to the yaml files in openstates/people, the string matching code
is in
https://github.com/openstates/openstates-core/blob/main/openstates/importers/bills.py
but likely will only have minimal changes since it already incorporates
aliases.  From herein it is largely a less interesting data problem, but if
you're able to help generate alias tables we can work to get those into the
people repository.

**Comment by jamesturk** [comment]
gonna close this one out, let's keep discussion on #22
