### ISSUE TITLE
MA: adapt scraper for 2021 site changes once a bit more data is present

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#225]
As of today, MA looks like they may be changing how they present data a bit.

The main change is that the information seems to be on a single page instead of subpages, which would mean a faster scrape.

An example of an old page, where each piece of info was on a subpage: 
https://malegislature.gov/Bills/191/S40 

But a new page looks different, with data inline:
https://malegislature.gov/Bills/192/SD6

Other things to check out:
- actions are not yet present, @showerst commented them out
- sponsor names should be cleaned up consistently before the comparison for duplicates

**Comment by showerst** [comment]
In case someone gets to it before i do, 

https://github.com/openstates/openstates-scrapers/blob/main/scrapers/ma/bills.py#L271

We're checking the cosponsor name against the list of sponsors, THEN doing some cleanup on it before saving. 

We should be doing the cleanup first before the comparison to make sure we don't dupe, and also move it to a function since we're applying the same code to sponsors

There are also some pretty fragile xpaths in there, so do a sweep once everything is up to see if we got lucky and they added classes or ids.

**Comment by jamesturk** [comment]
also currently seeing duplicate bills in pagination, I think this might just be because they're loading bills as we scrape.  will check this out after they seem to have stopped uploading bills to see if we need to adapt at all

**Comment by jamesturk** [comment]
@showerst OK to close this one?

**Comment by LauraBula** [comment]
THANK YOU!
