### ISSUE TITLE
Virginia - 2021 Special Session I

### ISSUE THREAD

**Issue by jchapman146** [openstates/issues#332]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:** I don't see the 2021 Special Session I from Virginia. Several bills from the Regular Session were continued during the special session. Can you add the special session? Examples of bills which were continued include SB 1392 and HB 2307.

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**

**Comment by showerst** [comment]
This is a weird special case -- VA's 2021 special carried over all the bills from the regular, so rather than duplicate all the bills, we scraped the special session actions as part of the regular. 

SB 1392: 

https://openstates.org/va/bills/2021/SB1392/
https://lis.virginia.gov/cgi-bin/legp604.exe?212+sum+SB1392

This is actually the only time we've ever done this, generally we create specials when the state does.

**Comment by jchapman146** [comment]
Agreed, this is not the typical process. On your openstates page for SB 1392, the links to the state website are to the regular session, which is hard to then navigate to the correct text. Further, the "View the Latest Bill Text" returns a bad query page from the state site. Thanks!

**Comment by showerst** [comment]
We have an open bug for that issue, trying to figure out the right way to handle it w/out duping the bill texts. If you'd like to track it -- https://github.com/openstates/issues/issues/328
