### ISSUE TITLE
OH HR 35 not ingested, presumably because title missing

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#379]
**Issue Description:** OH HR 35 is missing from Open States data.  It looks like it's probably missing because there is weirdly no title to the bill (probably somebody's typo/oversight). However it seems like a real bill: it has sponsors and a version.

Can we ingest a bill with a blank title? or set title to "(unknown)" or something?

(I did send a report email to webmaster@lis.state.oh.us)

**URL where this issue may be seen (API or OpenStates.org):** https://openstates.org/search/?query=hr+35&state=oh

**Source URL of correct data if applicable:**

https://www.legislature.ohio.gov/legislation/search?generalAssemblies=134&keywords=HR%2035&legislationTypes=HB,HR,HCR,HJR&pageSize=10&sort=Number&start=1
https://www.legislature.ohio.gov/legislation/legislation-summary?id=GA134-HR-35

**Comment by showerst** [comment]
Generally when something is model-defyingly broken we either hard-code a special case fix or wait for the state. 

In this case, we could pull the title from the [version](https://search-prod.lis.state.oh.us/solarapi/v1/general_assembly_134/resolutions/hr35/IN/00?format=pdf) and just say if bill = ... and session = ... then title = whatever. Since it's clear this is just a state issue i'm fine w/ a special case in the code as long as james doesn't care, we do it elsewhere.

FWIW i'd prefer a special case to relaxing a model constraint.

**Comment by showerst** [comment]
Side note, if they do this in multiple places and this isn't just a one-off, maybe we should consider setting it to 'No title provided' or something in the scraper.

**Comment by jessemortenson** [comment]
It might be a one off, I'm not sure. I'm fine with a special case and "No title provided" - created a PR
