### ISSUE TITLE
Restore committee data with a new process

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#45]
There are a lot of issues on committee information, but I don't think a lot of people interested in making PRs for it.  Committee scrapers are very prone to breakage, maybe the highest of all the ones we maintain.  

This leaves us in a tough spot, should we continue to provide it?  Are people using this data?  Is anyone interested in helping maintain it?

**Comment by showerst** [comment]
I had some more time to look at this, and have a few thoughts:

1. I agree maintaining the full scrapers is too much for our current resources
1. That said, it would be nice to have a list of committees and aliases with some kind of canonical IDs for things like resolving sponsorships and meetings.
1. These don't change very often, and going into 2021 Openstates (or Govhawk for that matter) should have a 95% accurate list of state committees that currently exist. 
1. Maybe instead of maintaining scrapers for it, we move to a YAML model like openstates-people and take PRs? 
1. I don't think it makes sense to track contact and membership information, unless we can get a sponsor to do the work, but keeping a list of names and aliases seems doable.

Just as a proof of concept i whipped up a quick list of some CA committees in a sample format --

https://gist.github.com/showerst/56509d68dbd7527c531f7e36cebff194

I'm thinking we could do one file per jurisdiction. Haven't thought out 'retirements' (other than an end_date key).

The big obvious downside is that this doesn't come with sourced scrapers to run the updates, but we could provide small utility scripts for adding/retiring a com.

What are people's thoughts on this?

1. Is it worth pursuing this?
1. I could do a one time dump to get us started, and try to add them as i see new ones, but i'm concerned about it going stale.
2. Contact info was impossible to keep up to date, but a website URL might be manageable? Are there other keys that make sense to include/exclude? 

@jamesturk @azban

**Comment by jamesturk** [comment]
I'm on board with this, lots of people have reached out about supporting
committees again but balk at the amount of work to actually track
members.   I don't see it happening any time soon.

From my point of view, the most useful thing will wind up being the
aliases, I don't see us using many other fields besides those- so this
works well from my perspective.

One thought: In other places where we have aliases they can have an
optional start & end date, so we might want to consider supporting that by
making the aliases a list of objects instead of just strings?
(e.g.

aliases:
     - name: Assembly Select Committee on Sustainable and Organic
Agriculture
)
which would give the future flexibility to add end_date as needed without
changing too much
