### ISSUE TITLE
Intercepting missing files with self.get

### ISSUE THREAD

**Issue by showerst** [openstates/issues#465]
@jamesturk -- In the latest special, VA (an ftp based scraper) is just not posting some files to the FTP server that the scraper expects, like the file of amendments. This causes the scraper to bomb out, because self.get sleeps in a loop if it gets a 404.

I've turned off extra features in the scraper for specials, but my preference would just be to run those functions and return if there's no file for them to parse, in case they post the file later.

I tried doing something like this:

```
        try:
            resp = self.get(self._url_base + "Amendments.csv").text
        except scrapelib.HTTPError:
            return
```

but all I get is 

```
10:32:59 WARNING scrapelib: got error while retrieving ftp://<credentials removed>@legis.virginia.gov/fromdlas/csv213/Amendments.csv sleeping for 10 seconds before retry
```

Is there a way to catch 404 errors in a call to self.get ? I think we looked into this once in the past, but I forget the outcome. No biggie if not, just hoping to avoid having someone rewrite all those calls to use requests.

**Comment by jamesturk** [comment]
I think the issue here is that the FTP adapter works a bit differently since requests doesn't handle FTP for us.

For normal HTTP requests we have retry_on_404=False (which is default), but we can't distinguish that this is a 404 since it isn't from HTTP.  I don't think there's a way to avoid the retry then, but if waiting for the retries to time out works it should still be possible to catch the FTPError (not HTTPError) and continue processing unless I'm misunderstanding something

**Comment by showerst** [comment]
Cool, thanks, that makes sense. 

I was hoping to avoid the pause series entirely for FTP, but it's not that big a deal.
