### ISSUE TITLE
Outdated Legislative/Congressional District Information for Arizona

### ISSUE THREAD

**Issue by engagedaz** [openstates/issues#644]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
The legislative/congressional district map data is outdated for the State of Arizona.

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**
https://redistricting-irc-az.hub.arcgis.com/pages/official-maps

**Comment by NewAgeAirbender** [comment]
Due to the fact that there are two valid sets of boundaries, elections & elected, until the end of the year, Open States will continue to provide who is currently in office in each district. Boundaries changed due to redistricting will be updated before 2023 sessions, along with newly elected legislators.
