### ISSUE TITLE
2 U.S. Senators don't show up in People query results

### ISSUE THREAD

**Issue by mdimichele** [openstates/issues#666]
**API Query (be sure to omit API key!!!):**
```
https://v3.openstates.org/people.geo?lat=41.8306926&lng=-87.6263604&include=links&apikey=xxxxxx&org_classification=government

**Please describe the issue:**
The query above returns 3 people in the resutlts. My 2 state representatives and my U.S. House representative.  But, unlike your page ( https://openstates.org/find_your_legislator/?lat=42.272705&lon=-89.117845&address=405%20s.%20independence%20ave,%20rockford,%20il&state=) I cannot figure out how to access the 2 senators for the state.  Nor can I figure out how to access the contact information for all 5 people.

I know I am using peoplegeo.  I tried it with the people api request as well.  Same issue.

Is there a guide how to access ALL of the different data.  From what I am seeing I may have to make multiple API calls to get all 5 people and all of their contact information for any geolocation.  There should be 5 people.

Thanks for the help in advance,

Mike

**Comment by NewAgeAirbender** [comment]
Hey Mike, 

Currently the logic that returns the federal legislators as well as state on the Find My Legislator page is on the [openstates.org repo](https://github.com/openstates/openstates.org/blob/197c6a6341a6a469807cf2085b29d4196fec9e8d/public/views/legislators.py#L10) instead of the API V3. We do have a backlog ticket to add them to the people.geo response, but for immediate needs you can access them by adding `classification:["upper", "lower", "legislature", "party"]` to a people call to the GraphQL API, where you can specify what data you want about them like this [example here](https://docs.openstates.org/api-v2/examples/#search-for-legislators-that-represent-a-given-area).

Hope that helps!
Rylie
