### ISSUE TITLE
WV Scraper needs fixes to how it selects sessions

### ISSUE THREAD

**Issue by showerst** [openstates/issues#690]
State: WV

Bill scraper has a bunch of places where it assumes the session being scraped is the last one in the __init__.py list, which is wrong, and will lead to bad results if you scrape an older session, especially a special.

`self.jurisdiction.legislative_sessions[-1]` 

This is just a note to fix that when someone has some free time.

**Comment by jessemortenson** [comment]
This has been around for a while but I'm going to try to get it cleaned up before end of year here. To add a little more context:

The logic in a scraper should be operating entirely on the `session` variable passed into the `scrape()` function. There is logic in WV that does that, but also logic that assumes that the `session` is the same as `self.jurisdiction.legislative_sessions[-1]`, which is not going to be true all the time. For example, if you intentionally select a `session` to be scraped that is not the last element in that array, the [wrong URL could be assembled around line 78](https://github.com/openstates/openstates-scrapers/blob/ba26299f5aeb7f8466f6d2248bfe717a51857b21/scrapers/wv/bills.py#L78). Where data is needed from the dict in that list, the dict should first be found by matching the `session` identifier to the dict.

Should be testable by passing in a past session as a commandline argument in order to scrape an older, non-special session, eg `session=2024`
