### ISSUE TITLE
Texas has redistricted recently. Your tool -- which is marvelous, btw -- does not reflect these changes. I really hope that someone there can update Texas and any other states whose districts have been ... adjusted. (Pause to swear a lot about this.) 

### ISSUE THREAD

**Issue by MBFoster1** [openstates/issues#721]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**

**Comment by NewAgeAirbender** [comment]
Due to the fact that there are two valid sets of boundaries, elections & elected, until the end of the year, Open States will continue to provide who is currently in office in each district. Boundaries changed due to redistricting will be updated before 2023 sessions, along with newly elected legislators.
