### ISSUE TITLE
Question: why does the PostgreSQL data dump say it's from January 2021?

### ISSUE THREAD

**Issue by arheinjohnson** [openstates/issues#737]
Thank you for this awesome project.

**Issue Description:**
The update schedule for PostgreSQL data dump says this data is updated monthly, but the schema & data downloads say they are from January 2021? Are they all over a year outdated?

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/data/

**Comment by johnseekins** [comment]
The link is to a monthly pgdump file. If you change the time in the link (in this case from 2021 to 2022 or from 01 to 06), you'll receive a different file. I think the bug here is just that the website is linking to a static file.

(e.g. https://data.openstates.org/postgres/monthly/2022-06-public.pgdump works fine)

**Comment by arheinjohnson** [comment]
Thank you!
