### ISSUE TITLE
SC: Scraper task failing most days

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#77]
**Issue Description:** SC scraper is failing most days, mostly on HTTP errors stemming from requests to the SC site. Seems like requests being dropped at the server side?

`ConnectionResetError: [Errno 104] Connection reset by peer`
`http.client.RemoteDisconnected: Remote end closed connection without response`

Seems to be throwing the error on a different URL each time.

**URL where this issue may be seen (API or OpenStates.org):** https://bobsled.openstates.org/task/SC-scrape

Would it make sense to make changes for more retries + ignore errors? like:

```
self.raise_errors = False
self.retry_attempts = 5
```

**Comment by jamesturk** [comment]
Worth a shot 👍  SC's been bad for a while, I'll take a look at adding this or would take a PR if you get to it first

**Comment by jamesturk** [comment]
added in https://github.com/openstates/openstates-scrapers/commit/c03097a982a8513fcc2ee276980532d19879e43a

will monitor over the next week to see what this does on bobsled runs

**Comment by jamesturk** [comment]
I think I need to look at the type of error being thrown and get scrapelib retries to work with it.

**Comment by jamesturk** [comment]
dug in a bit today & realized that call isn't using scrapelib-- which is why it isn't retrying/etc. 

it looks like we switched to using urllib so we could try to handle partial responses a while ago

going to push a version that uses scrapelib with retries to see if that fixes this new error without resurfacing the old error, if it is still flaky one option might be to try without subjects since it seems like that is the problematic endpoint (at least it is the only one that we have this special logic for)

**Comment by jamesturk** [comment]
https://github.com/openstates/openstates-scrapers/commit/9860b41bbcf8844c3cce8b4c4a1cd57abfd30d10

<s>will probably revert this after a run or two </s>

nevermind, this wasn't right -- trying to run without the subject code next

**Comment by showerst** [comment]
(didn't check the history) I think that swap was either me or sometone at govhawk, we were getting a bunch of weird server errors because SC was cutting off responses or sending invalid lengths back. 

Hopefully that's fixed on their end now and we can switch back!

**Comment by jamesturk** [comment]
That service still seems to be serving those incomplete responses, so I reverted that pretty quickly.

Looking at the scrape history: https://bobsled.openstates.org/task/SC-scrape I think 100% of failures have been in that portion.  That might not be fair, since it happens first, but we didn't have the unusual code workarounds on the other requests, so it may be just the subjects endpoint that is troublesome.

I've temporarily commented out the call to scrape_subjects to see if SC finishes (a long scrape in prod, but no failures so far). If this works then I'm inclined to leave subject scraping disabled for the foreseeable future.  Or maybe we can find another source of the subject data? Or maybe we do without?

**Comment by showerst** [comment]
Count me as one vote to leaving it out if it effects scraper finish-chances.

**Comment by jamesturk** [comment]
With the exception of a weird timeout issue (which we'll keep an eye on) and the day I broke all the scrapers at once, SC has run successfully since adding this.  Going to close this issue out for now, we'll go forward without subjects.

**Comment by alexobaseki** [comment]
SC scraper is still having timeout issues. Time out over 50% in the last 2 weeks [https://bobsled.openstates.org/task/SC-scrape](https://bobsled.openstates.org/task/SC-scrape). Wondering if we should open a new issue for this or continue from here?
