### ISSUE TITLE
New NM Committee Scraper

### ISSUE THREAD

**Issue by sroomf** [openstates/issues#867]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for New Mexico.

It should scrape these pages for the [Senate committees](https://www.nmlegis.gov/Committee/Senate_Standing), [House committees](https://www.nmlegis.gov/Committee/House_Standing), and [Joint Interim committees](https://www.nmlegis.gov/Committee/Interim) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nm/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also parses HTML pages, for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by JPMartinezClaeys** [comment]
I'll work in NM

**Comment by sroomf** [comment]
hi @JPMartinezClaeys, thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)

**Comment by JPMartinezClaeys** [comment]
Ok @sroomf, I'll take that deadline into account.

**Comment by chrisyamas** [comment]
Hi @JPMartinezClaeys, if you do have any code written on this, please push it to [your forked repo](https://github.com/JPMartinezClaeys/openstates-scrapers) and even feel free [to make a pull request to the upstream repo](https://github.com/openstates/openstates-scrapers/pulls). No worries if you don't have any code to commit/push, but also don't hesitate to ask any question on how to push to the repo or make a PR, if you'd like any guidance on that!

While are reassigning this issue due to time constraints, please let us know in the comments on any unassigned issues if you're still interested in contributing to the Open States project! You can also reach out to me at [christopher@civiceagle.com](mailto:christopher@civiceagle.com) if you want to learn more about the project and how you could contribute!
